version: "3"

services:
  nginx:
    image: nginx
    container_name: 'nginx'
    restart: unless-stopped
    volumes:
      - ./sources:/var/www
      - ./config/nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    command: [ nginx-debug, '-g', 'daemon off;' ]
    ports:
      - "80:80"
      - "443:443"
    networks:
      - project-network

  redis:
    image: redis:alpine
    restart: 'unless-stopped'
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - project-network

  api:
    platform: linux/x86_64
    build:
      context: ./bin/php
      dockerfile: Dockerfile
    container_name: api
    restart: 'unless-stopped'
    working_dir: /var/www/
    volumes:
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./sources:/var/www
    networks:
      - project-network

    db:
      image: mysql:8.0
      container_name: db
      restart: unless-stopped
      tty: true
      ports:
        - "33061:3306"
      environment:
        MYSQL_DATABASE: laravel
        MYSQL_ROOT_PASSWORD: your_mysql_root_password
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql
      volumes:
        - ./config/dbdata:/var/lib/mysql/
      networks:
        - project-network

networks:
  project-network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.1.0.0/24
